import { useState } from 'react';
import { Link } from 'react-router-dom';
import Header from '@/components/feature/Header';
import Footer from '@/pages/home/components/Footer';
import FloatingWhatsApp from '@/pages/home/components/FloatingWhatsApp';
import MobileStickyBar from '@/pages/home/components/MobileStickyBar';
import ShoulderPainHero from './HeroSection';
import { useScrollAnimation } from '@/hooks/useScrollAnimation';
import RelatedPatientStories from '@/components/feature/RelatedPatientStories';

const SYMPTOMS = [
  { icon: 'ri-arrow-up-line', title: 'Pain Lifting Arm', desc: 'Sharp pain when reaching overhead, combing hair, or reaching behind the back. A classic rotator cuff sign.' },
  { icon: 'ri-moon-line', title: 'Night Pain', desc: 'Aching that worsens at night, especially when lying on the affected shoulder. Disturbs sleep and indicates significant pathology.' },
  { icon: 'ri-lock-line', title: 'Stiffness', desc: 'Progressive loss of shoulder movement — difficulty with daily tasks like dressing or reaching for objects on shelves.' },
  { icon: 'ri-alert-line', title: 'Weakness', desc: 'Noticeable loss of strength when lifting objects or performing overhead activities. May indicate a full-thickness rotator cuff tear.' },
  { icon: 'ri-restart-line', title: 'Instability', desc: 'Sensation of the shoulder slipping out of place or feeling loose. Common in recurrent dislocations and labral tears.' },
  { icon: 'ri-volume-up-line', title: 'Clicking & Catching', desc: 'Audible clicking or catching sensation during shoulder movement, often indicating labral pathology or impingement.' },
];

const CAUSES = [
  { title: 'Rotator Cuff Tear', desc: 'Partial or complete tear of the tendons surrounding the shoulder joint — from acute injury or chronic degeneration. Most common in individuals over 40.' },
  { title: 'Frozen Shoulder', desc: 'Adhesive capsulitis causing progressive stiffness and pain. Develops gradually over months and is more common in diabetics and thyroid patients.' },
  { title: 'Shoulder Impingement', desc: 'Pinching of rotator cuff tendons between the humeral head and acromion during overhead movements. Causes pain with reaching and lifting.' },
  { title: 'Shoulder Dislocation', desc: 'The humeral head slips out of the glenoid socket — usually from trauma. Can become recurrent if the labrum (Bankart lesion) is damaged.' },
  { title: 'Arthritis', desc: 'Osteoarthritis or rheumatoid arthritis affecting the shoulder joint. Causes gradual pain, stiffness, and loss of function over time.' },
  { title: 'Biceps Tendinitis', desc: 'Inflammation of the long head of biceps tendon in the bicipital groove. Causes anterior shoulder pain worsened by elbow flexion.' },
];

const TREATMENTS = [
  { icon: 'ri-psychotherapy-line', title: 'Physiotherapy', desc: 'Targeted exercises for rotator cuff strengthening, scapular stabilization, and range-of-motion restoration. First-line for most shoulder conditions.' },
  { icon: 'ri-drop-line', title: 'Injections', desc: 'Corticosteroid injections for impingement and bursitis. PRP therapy for partial rotator cuff tears to promote natural healing.' },
  { icon: 'ri-camera-line', title: 'Arthroscopy', desc: 'Minimally invasive keyhole surgery for rotator cuff repair, labral repair (Bankart), subacromial decompression, and biceps tenodesis.' },
  { icon: 'ri-surgical-mask-line', title: 'Rotator Cuff Repair', desc: 'Arthroscopic repair of torn rotator cuff tendons using suture anchors. Modern double-row techniques provide stronger fixation.' },
  { icon: 'ri-shield-line', title: 'Shoulder Stabilization', desc: 'Arthroscopic Bankart repair or Latarjet procedure for recurrent shoulder dislocations to restore stability and prevent future episodes.' },
  { icon: 'ri-tools-line', title: 'Shoulder Replacement', desc: 'Anatomic or reverse total shoulder arthroplasty for end-stage arthritis. Reverse replacement is particularly effective for rotator cuff arthropathy.' },
];

const BENEFITS = [
  { icon: 'ri-sun-line', title: 'Sleep Through the Night', desc: 'Treating the root cause of night pain restores restful sleep — one of the first improvements patients report.' },
  { icon: 'ri-arrow-up-circle-line', title: 'Reach Overhead Again', desc: 'Regain the ability to perform overhead activities without pain — from daily grooming to sports and hobbies.' },
  { icon: 'ri-shield-check-line', title: 'Prevent Further Damage', desc: 'Early treatment of partial tears prevents progression to complete tears that require more extensive surgery.' },
  { icon: 'ri-speed-up-line', title: 'Faster Return to Activity', desc: 'Arthroscopic techniques mean smaller incisions, less pain, and quicker rehabilitation compared to open surgery.' },
];

const RECOVERY_STEPS = [
  { week: 'Week 1-4', icon: 'ri-rest-time-line', desc: 'Sling immobilization. Pendulum exercises. Pain and swelling management. Avoid active shoulder movement during this protective phase.' },
  { week: 'Week 4-8', icon: 'ri-psychotherapy-line', desc: 'Begin passive and active-assisted range of motion. Physiotherapy focused on regaining movement without stressing the repair.' },
  { week: 'Week 8-16', icon: 'ri-walk-line', desc: 'Progressive strengthening exercises. Return to light daily activities. Scapular stabilization training.' },
  { week: 'Month 4-6', icon: 'ri-trophy-line', desc: 'Advanced strengthening. Return to recreational sports and overhead activities. Full recovery achieved gradually.' },
];

const FAQS = [
  { q: 'What is the most common cause of shoulder pain?', a: 'Rotator cuff pathology — including tendinitis, impingement, and tears — is the most common cause. Dr. Sagar can diagnose the exact problem through physical examination and imaging.' },
  { q: 'Can a rotator cuff tear heal without surgery?', a: 'Partial tears often respond well to physiotherapy, activity modification, and injections. Complete tears generally do not heal on their own and may require surgical repair, especially in active individuals.' },
  { q: 'What is frozen shoulder and how long does it last?', a: 'Frozen shoulder (adhesive capsulitis) progresses through three phases: freezing (painful, 2-9 months), frozen (stiff, 4-12 months), and thawing (recovery, 5-24 months). Treatment can accelerate recovery.' },
  { q: 'How is shoulder arthroscopy performed?', a: 'Through 2-4 small incisions (5-10mm each), a camera and specialized instruments are inserted. Dr. Sagar repairs damaged structures while viewing them on a high-definition monitor. Most patients go home the same day.' },
  { q: 'When can I drive after shoulder surgery?', a: 'Typically 4-6 weeks for left shoulder surgery, and 6-8 weeks for right shoulder surgery (in right-handed drivers). You must be off narcotic pain medication and able to safely control the vehicle.' },
  { q: 'What is the consultation process for shoulder pain?', a: 'Dr. Sagar will take a detailed history, perform a focused shoulder examination including special tests, review any imaging, and provide a clear diagnosis with treatment recommendations.' },
];

const RELATED = [
  { id: 'sports-injuries', icon: 'ri-run-line', label: 'Sports Injuries' },
  { id: 'joint-replacement', icon: 'ri-surgical-mask-line', label: 'Joint Replacement' },
  { id: 'arthritis', icon: 'ri-hand-heart-line', label: 'Arthritis' },
  { id: 'rehabilitation', icon: 'ri-mental-health-line', label: 'Rehabilitation' },
];

function RevealBlock({ children, delay = '', className = '' }: { children: React.ReactNode; delay?: string; className?: string }) {
  const { ref, isVisible } = useScrollAnimation(0.1);
  return (<div ref={ref} className={`${className} transition-all duration-800 ${delay} ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>{children}</div>);
}

export default function ShoulderPainPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  return (
    <main className="min-h-screen bg-background-50">
      <Header /><ShoulderPainHero />
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock><div className="grid grid-cols-1 lg:grid-cols-2 gap-10 md:gap-16 items-center"><div><span className="text-indigo-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Overview</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3 mb-5">Understanding <span className="text-indigo-600">Shoulder Pain</span></h2><div className="space-y-4 text-foreground-600 text-sm leading-relaxed"><p>The shoulder is the most mobile joint in the human body — and that mobility comes at a cost. It's also one of the most commonly injured joints, affecting everyone from athletes to office workers.</p><p>Dr. Sagar K V diagnoses and treats the full spectrum of shoulder conditions using <strong className="text-foreground-900">evidence-based protocols</strong>. Most shoulder problems can be managed without surgery — and when surgery is needed, arthroscopic techniques minimize recovery time.</p><p>Shoulder pain shouldn't be ignored. What starts as a minor impingement can progress to a full-thickness rotator cuff tear if left untreated. <strong className="text-foreground-900">Early diagnosis leads to better outcomes.</strong></p></div></div><div className="relative"><div className="w-full aspect-[4/3] rounded-3xl overflow-hidden bg-gradient-to-br from-indigo-100 via-blue-50 to-background-100 border border-background-200/70 flex items-center justify-center"><div className="text-center p-8"><div className="w-20 h-20 mx-auto mb-4 rounded-full bg-indigo-100 flex items-center justify-center"><i className="ri-arrow-up-circle-line text-indigo-600 text-3xl"></i></div><span className="text-foreground-400 text-sm">Shoulder Joint Illustration</span></div></div></div></div></RevealBlock></div></section>
      <section className="py-16 md:py-24 bg-background-100"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-indigo-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Symptoms</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Recognizing <span className="text-indigo-600">Shoulder Issues</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">{SYMPTOMS.map((s,i)=>(<RevealBlock key={i} delay={`delay-${i*100}`}><div className="bg-background-50 border border-background-200/70 rounded-2xl p-5 md:p-6 h-full"><div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center mb-4"><i className={`${s.icon} text-indigo-600 text-lg`}></i></div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-2">{s.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{s.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-indigo-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Causes</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">What's Causing Your <span className="text-indigo-600">Shoulder Pain?</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{CAUSES.map((c,i)=>(<RevealBlock key={i} delay={`delay-${i*80}`}><div className="flex gap-4 p-5 rounded-2xl border border-background-200/70 bg-background-50 hover:border-indigo-200/50 transition-all duration-300 group cursor-default"><div className="w-2 rounded-full bg-indigo-400/40 group-hover:bg-indigo-500 shrink-0 transition-colors duration-300" /><div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-1.5">{c.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{c.desc}</p></div></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-secondary-600 relative overflow-hidden"><div className="absolute inset-0 pointer-events-none"><div className="absolute top-0 right-0 w-96 h-96 rounded-full bg-indigo-500/8 blur-[120px]" /></div><div className="max-w-6xl mx-auto px-4 md:px-8 relative z-10"><RevealBlock className="text-center mb-12"><span className="text-indigo-400 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Treatment Options</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-white mt-3">How Dr. Sagar Treats <span className="text-indigo-400">Shoulder Pain</span></h2></RevealBlock><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">{TREATMENTS.map((t,i)=>(<RevealBlock key={i} delay={`delay-${i*80}`}><div className="glass-dark rounded-2xl p-5 md:p-6 h-full group hover:-translate-y-1 transition-all duration-400"><div className="w-11 h-11 rounded-xl bg-indigo-400/15 flex items-center justify-center mb-4 group-hover:bg-indigo-400/25 transition-colors duration-300"><i className={`${t.icon} text-indigo-300 text-xl`}></i></div><h3 className="font-heading font-semibold text-white text-sm mb-2">{t.title}</h3><p className="text-white/45 text-xs leading-relaxed">{t.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-indigo-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Why Act Now</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Benefits of <span className="text-indigo-600">Early Treatment</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-5">{BENEFITS.map((b,i)=>(<RevealBlock key={i} delay={`delay-${i*100}`}><div className="text-center p-6 rounded-2xl border border-background-200/70 bg-background-50"><div className="w-14 h-14 mx-auto mb-4 rounded-full bg-indigo-50 flex items-center justify-center"><i className={`${b.icon} text-indigo-600 text-2xl`}></i></div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-2">{b.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{b.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-100"><div className="max-w-4xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-indigo-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Recovery</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Shoulder <span className="text-indigo-600">Rehabilitation</span></h2></RevealBlock><div className="relative"><div className="absolute left-[19px] md:left-[23px] top-4 bottom-4 w-0.5 bg-indigo-200/60" /><div className="space-y-6">{RECOVERY_STEPS.map((step,i)=>(<RevealBlock key={i} delay={`delay-${i*150}`}><div className="flex gap-5"><div className="relative z-10 w-10 h-10 md:w-12 md:h-12 rounded-full bg-indigo-500 flex items-center justify-center shrink-0 mt-0.5"><span className="text-white font-heading font-bold text-xs">{i+1}</span></div><div className="bg-background-50 border border-background-200/70 rounded-2xl p-5 flex-1"><div className="flex items-center gap-2 mb-2"><i className={`${step.icon} text-indigo-600`}></i><span className="font-heading font-semibold text-foreground-900 text-sm">{step.week}</span></div><p className="text-foreground-500 text-xs leading-relaxed">{step.desc}</p></div></div></RevealBlock>))}</div></div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-3xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-10"><span className="text-indigo-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">FAQ</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Shoulder Pain <span className="text-indigo-600">Questions</span></h2></RevealBlock><div className="space-y-3">{FAQS.map((faq,i)=>(<div key={i} className={`border rounded-2xl overflow-hidden transition-all duration-300 ${openFaq===i?'border-indigo-200 bg-background-50':'border-background-200/70 bg-background-50 hover:border-indigo-100'}`}><button onClick={()=>setOpenFaq(openFaq===i?null:i)} className="w-full flex items-center justify-between px-5 py-4 text-left cursor-pointer"><span className={`font-heading font-semibold text-sm pr-4 transition-colors duration-300 ${openFaq===i?'text-indigo-600':'text-foreground-900'}`}>{faq.q}</span><div className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 transition-all duration-300 ${openFaq===i?'bg-indigo-500 text-white rotate-45':'bg-background-100 text-foreground-400'}`}><i className="ri-add-line text-sm"></i></div></button><div className={`transition-all duration-400 overflow-hidden ${openFaq===i?'max-h-[400px] opacity-100':'max-h-0 opacity-0'}`}><div className="px-5 pb-5 text-foreground-500 text-sm leading-relaxed">{faq.a}</div></div></div>))}</div></div></section>
      <section className="py-16 md:py-20 bg-gradient-to-r from-indigo-700 to-blue-700 relative overflow-hidden"><div className="absolute inset-0"><div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] rounded-full bg-white/5 blur-[100px]" /></div><div className="max-w-3xl mx-auto px-4 md:px-8 text-center relative z-10"><RevealBlock><h2 className="font-heading font-bold text-3xl md:text-4xl text-white mb-4">Ready to Move Freely Again?</h2><p className="text-white/70 text-sm md:text-base mb-8 max-w-lg mx-auto">Don't let shoulder pain limit your life. Call Dr. Sagar K V for expert diagnosis and treatment.</p><div className="flex flex-col sm:flex-row items-center justify-center gap-3"><a href="tel:+918197344754" className="px-8 py-3.5 bg-white text-indigo-700 font-heading font-semibold rounded-full text-sm hover:bg-white/95 transition-all duration-300 whitespace-nowrap cursor-pointer"><i className="ri-phone-line mr-2"></i>Call Now</a><a href="https://wa.me/918197344754" target="_blank" rel="noopener noreferrer" className="px-8 py-3.5 bg-white/15 border border-white/25 text-white font-heading font-semibold rounded-full text-sm hover:bg-white/25 transition-all duration-300 whitespace-nowrap cursor-pointer"><i className="ri-whatsapp-line mr-2"></i>WhatsApp</a></div></RevealBlock></div></section>

      <RelatedPatientStories relevantSlugs={['shoulder-arthroscopy-42']} />

      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-10"><span className="text-foreground-400 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Explore Related</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Related <span className="text-indigo-600">Treatments</span></h2></RevealBlock><div className="flex flex-wrap items-center justify-center gap-3">{RELATED.map((r)=>(<Link key={r.id} to={`/treatments/${r.id}`} className="flex items-center gap-2.5 px-5 py-3 rounded-full border border-background-200/70 bg-background-50 text-foreground-600 hover:border-indigo-200 hover:text-indigo-600 text-sm font-medium transition-all duration-300 cursor-pointer whitespace-nowrap"><i className={`${r.icon} text-base`}></i>{r.label}</Link>))}</div></div></section>
      <Footer /><FloatingWhatsApp /><MobileStickyBar />
    </main>
  );
}
