import { useState } from 'react';
import { Link } from 'react-router-dom';
import Header from '@/components/feature/Header';
import Footer from '@/pages/home/components/Footer';
import FloatingWhatsApp from '@/pages/home/components/FloatingWhatsApp';
import MobileStickyBar from '@/pages/home/components/MobileStickyBar';
import FootAnkleHero from './HeroSection';
import { useScrollAnimation } from '@/hooks/useScrollAnimation';
import RelatedPatientStories from '@/components/feature/RelatedPatientStories';

const SYMPTOMS = [
  { icon: 'ri-footprint-line', title: 'Heel Pain', desc: 'Sharp pain in the heel, especially with first steps in the morning. Classic plantar fasciitis, often from prolonged standing or poor footwear.' },
  { icon: 'ri-contrast-drop-line', title: 'Ankle Swelling', desc: 'Persistent swelling around the ankle, worsening with activity. May indicate arthritis, tendonitis, or chronic instability.' },
  { icon: 'ri-alert-line', title: 'Instability', desc: 'Recurrent ankle giving way or frequent sprains. Suggests chronic ligament laxity that may require surgical stabilization.' },
  { icon: 'ri-shape-line', title: 'Deformity', desc: 'Visible deformities like bunions (hallux valgus), hammertoes, or flat foot — progressive conditions that worsen without treatment.' },
  { icon: 'ri-close-circle-line', title: 'Difficulty Walking', desc: 'Pain with every step, limping, or inability to walk normal distances. Significantly impacts daily activities and quality of life.' },
  { icon: 'ri-moon-line', title: 'Night Pain', desc: 'Burning or aching pain at night, often from nerve compression (tarsal tunnel syndrome) or inflammatory arthritis.' },
];

const CAUSES = [
  { title: 'Plantar Fasciitis', desc: 'Inflammation of the thick band of tissue running across the bottom of the foot. Most common cause of heel pain — often related to foot mechanics.' },
  { title: 'Ankle Sprains', desc: 'Stretching or tearing of ankle ligaments from twisting injuries. Repeated sprains lead to chronic instability requiring ligament reconstruction.' },
  { title: 'Achilles Tendinitis', desc: 'Overuse injury of the Achilles tendon causing pain at the back of the heel. Common in runners and middle-aged recreational athletes.' },
  { title: 'Bunions', desc: 'Progressive bony bump at the base of the big toe causing pain, difficulty fitting shoes, and altered walking pattern. Often hereditary.' },
  { title: 'Flat Foot Deformity', desc: 'Loss of the foot arch causing foot fatigue, pain, and abnormal gait. Can be flexible (present since childhood) or acquired (posterior tibial tendon dysfunction).' },
  { title: 'Diabetic Foot', desc: 'Neuropathy, poor circulation, and increased infection risk in diabetic patients. Requires specialized multidisciplinary care and vigilant monitoring.' },
];

const TREATMENTS = [
  { icon: 'ri-psychotherapy-line', title: 'Physiotherapy', desc: 'Stretching and strengthening exercises for plantar fasciitis, ankle instability, and post-surgical rehabilitation.' },
  { icon: 'ri-footprint-line', title: 'Orthotics', desc: 'Custom-made shoe inserts to correct foot mechanics, support the arch, and redistribute pressure away from painful areas.' },
  { icon: 'ri-drop-line', title: 'Injections', desc: 'Corticosteroid injections for plantar fasciitis and arthritis. PRP therapy for chronic Achilles tendinitis to promote tissue healing.' },
  { icon: 'ri-camera-line', title: 'Ankle Arthroscopy', desc: 'Minimally invasive surgery for cartilage injuries, loose bodies, and ankle impingement through tiny incisions.' },
  { icon: 'ri-tools-line', title: 'Bunion Surgery', desc: 'Corrective osteotomy to realign the big toe, remove the bony prominence, and restore normal foot shape and function.' },
  { icon: 'ri-surgical-mask-line', title: 'Ankle Fusion', desc: 'Joint fusion surgery for end-stage ankle arthritis — eliminates pain by permanently joining bones together for stability.' },
];

const BENEFITS = [
  { icon: 'ri-walk-line', title: 'Walk Without Pain', desc: 'Treating foot and ankle conditions restores comfortable walking — the foundation of an active, independent lifestyle.' },
  { icon: 'ri-shield-check-line', title: 'Prevent Falls', desc: 'Stable, pain-free feet reduce fall risk, particularly important for elderly patients where falls can be catastrophic.' },
  { icon: 'ri-footprint-line', title: 'Proper Footwear', desc: 'Straighten deformities so you can wear normal shoes comfortably without specialized or oversized footwear.' },
  { icon: 'ri-speed-up-line', title: 'Stop Progression', desc: 'Early intervention prevents minor foot problems from becoming severe deformities requiring complex reconstructive surgery.' },
];

const RECOVERY_STEPS = [
  { week: 'Week 1-2', icon: 'ri-rest-time-line', desc: 'Rest, ice, elevation. Protected weight-bearing with crutches or walking boot. Pain and swelling management.' },
  { week: 'Week 2-6', icon: 'ri-psychotherapy-line', desc: 'Gradual increase in weight-bearing. Begin gentle range-of-motion exercises. Transition from boot to supportive footwear.' },
  { week: 'Week 6-12', icon: 'ri-walk-line', desc: 'Progressive strengthening and balance training. Return to most daily activities and walking without support.' },
  { week: 'Month 3-6', icon: 'ri-trophy-line', desc: 'Return to sports and high-impact activities. Full recovery with ongoing maintenance exercises and periodic follow-up.' },
];

const FAQS = [
  { q: 'What is the most common cause of heel pain?', a: 'Plantar fasciitis is the leading cause. It presents as sharp heel pain with first steps in the morning, typically improving with movement. Dr. Sagar can confirm the diagnosis and recommend appropriate treatment.' },
  { q: 'When does an ankle sprain need surgery?', a: 'Most ankle sprains heal with rest and physiotherapy. Surgery (ligament reconstruction) is considered when there is chronic instability with recurrent sprains despite adequate rehabilitation.' },
  { q: 'Can bunions be treated without surgery?', a: 'Wide-toe-box shoes, padding, and orthotics can relieve symptoms. However, bunions are progressive — they do not reverse without surgery. Dr. Sagar will discuss whether surgical correction is appropriate for your case.' },
  { q: 'What is diabetic foot care?', a: 'Diabetic patients need specialized foot monitoring due to reduced sensation and circulation. Regular check-ups, appropriate footwear, and prompt treatment of any wounds or infections are essential to prevent serious complications.' },
  { q: 'How long does foot surgery recovery take?', a: 'Recovery varies by procedure. Bunion surgery: 6-12 weeks for normal footwear. Ankle ligament reconstruction: 3-4 months for sports. Foot fusion: 3-6 months for full activity. Dr. Sagar provides detailed timelines for each procedure.' },
  { q: 'Is flat foot correctable in adults?', a: 'Flexible flat foot that developed in childhood usually does not require treatment. Acquired adult flat foot (posterior tibial tendon dysfunction) may need bracing, physiotherapy, or surgical reconstruction depending on severity.' },
];

const RELATED = [
  { id: 'sports-injuries', icon: 'ri-run-line', label: 'Sports Injuries' },
  { id: 'arthritis', icon: 'ri-hand-heart-line', label: 'Arthritis' },
  { id: 'fracture-care', icon: 'ri-shield-line', label: 'Fracture Care' },
  { id: 'rehabilitation', icon: 'ri-mental-health-line', label: 'Rehabilitation' },
];

function RevealBlock({ children, delay = '', className = '' }: { children: React.ReactNode; delay?: string; className?: string }) {
  const { ref, isVisible } = useScrollAnimation(0.1);
  return (<div ref={ref} className={`${className} transition-all duration-800 ${delay} ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>{children}</div>);
}

export default function FootAnklePage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  return (
    <main className="min-h-screen bg-background-50">
      <Header /><FootAnkleHero />
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock><div className="grid grid-cols-1 lg:grid-cols-2 gap-10 md:gap-16 items-center"><div><span className="text-teal-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Overview</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3 mb-5">Understanding <span className="text-teal-600">Foot & Ankle</span></h2><div className="space-y-4 text-foreground-600 text-sm leading-relaxed"><p>Your feet carry you through life — each foot contains 26 bones, 33 joints, and over 100 muscles, tendons, and ligaments. When something goes wrong, every step becomes a reminder.</p><p>Dr. Sagar K V treats the full spectrum of foot and ankle conditions. The good news: <strong className="text-foreground-900">90% of foot and ankle problems can be managed without surgery</strong>. From custom orthotics to physiotherapy, conservative care is always the starting point.</p><p>When surgery is needed, modern techniques — including minimally invasive bunion correction and arthroscopic ankle surgery — mean <strong className="text-foreground-900">less pain, smaller scars, and faster recovery</strong>.</p></div></div><div className="relative"><div className="w-full aspect-[4/3] rounded-3xl overflow-hidden bg-gradient-to-br from-teal-100 via-emerald-50 to-background-100 border border-background-200/70 flex items-center justify-center"><div className="text-center p-8"><div className="w-20 h-20 mx-auto mb-4 rounded-full bg-teal-100 flex items-center justify-center"><i className="ri-footprint-line text-teal-600 text-3xl"></i></div><span className="text-foreground-400 text-sm">Foot Anatomy Illustration</span></div></div></div></div></RevealBlock></div></section>
      <section className="py-16 md:py-24 bg-background-100"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-teal-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Symptoms</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">When Your <span className="text-teal-600">Feet Hurt</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">{SYMPTOMS.map((s,i)=>(<RevealBlock key={i} delay={`delay-${i*100}`}><div className="bg-background-50 border border-background-200/70 rounded-2xl p-5 md:p-6 h-full"><div className="w-10 h-10 rounded-xl bg-teal-50 flex items-center justify-center mb-4"><i className={`${s.icon} text-teal-600 text-lg`}></i></div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-2">{s.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{s.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-teal-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Causes</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Common <span className="text-teal-600">Conditions</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{CAUSES.map((c,i)=>(<RevealBlock key={i} delay={`delay-${i*80}`}><div className="flex gap-4 p-5 rounded-2xl border border-background-200/70 bg-background-50 hover:border-teal-200/50 transition-all duration-300 group cursor-default"><div className="w-2 rounded-full bg-teal-400/40 group-hover:bg-teal-500 shrink-0 transition-colors duration-300" /><div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-1.5">{c.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{c.desc}</p></div></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-secondary-600 relative overflow-hidden"><div className="absolute inset-0 pointer-events-none"><div className="absolute top-0 right-0 w-96 h-96 rounded-full bg-teal-500/8 blur-[120px]" /></div><div className="max-w-6xl mx-auto px-4 md:px-8 relative z-10"><RevealBlock className="text-center mb-12"><span className="text-teal-400 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Treatment Options</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-white mt-3">Foot & Ankle <span className="text-teal-400">Treatments</span></h2></RevealBlock><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">{TREATMENTS.map((t,i)=>(<RevealBlock key={i} delay={`delay-${i*80}`}><div className="glass-dark rounded-2xl p-5 md:p-6 h-full group hover:-translate-y-1 transition-all duration-400"><div className="w-11 h-11 rounded-xl bg-teal-400/15 flex items-center justify-center mb-4 group-hover:bg-teal-400/25 transition-colors duration-300"><i className={`${t.icon} text-teal-300 text-xl`}></i></div><h3 className="font-heading font-semibold text-white text-sm mb-2">{t.title}</h3><p className="text-white/45 text-xs leading-relaxed">{t.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-teal-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Why Act Now</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Benefits of <span className="text-teal-600">Timely Treatment</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-5">{BENEFITS.map((b,i)=>(<RevealBlock key={i} delay={`delay-${i*100}`}><div className="text-center p-6 rounded-2xl border border-background-200/70 bg-background-50"><div className="w-14 h-14 mx-auto mb-4 rounded-full bg-teal-50 flex items-center justify-center"><i className={`${b.icon} text-teal-600 text-2xl`}></i></div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-2">{b.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{b.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-100"><div className="max-w-4xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-teal-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Recovery</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Recovery <span className="text-teal-600">Roadmap</span></h2></RevealBlock><div className="relative"><div className="absolute left-[19px] md:left-[23px] top-4 bottom-4 w-0.5 bg-teal-200/60" /><div className="space-y-6">{RECOVERY_STEPS.map((step,i)=>(<RevealBlock key={i} delay={`delay-${i*150}`}><div className="flex gap-5"><div className="relative z-10 w-10 h-10 md:w-12 md:h-12 rounded-full bg-teal-500 flex items-center justify-center shrink-0 mt-0.5"><span className="text-white font-heading font-bold text-xs">{i+1}</span></div><div className="bg-background-50 border border-background-200/70 rounded-2xl p-5 flex-1"><div className="flex items-center gap-2 mb-2"><i className={`${step.icon} text-teal-600`}></i><span className="font-heading font-semibold text-foreground-900 text-sm">{step.week}</span></div><p className="text-foreground-500 text-xs leading-relaxed">{step.desc}</p></div></div></RevealBlock>))}</div></div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-3xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-10"><span className="text-teal-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">FAQ</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Foot & Ankle <span className="text-teal-600">Questions</span></h2></RevealBlock><div className="space-y-3">{FAQS.map((faq,i)=>(<div key={i} className={`border rounded-2xl overflow-hidden transition-all duration-300 ${openFaq===i?'border-teal-200 bg-background-50':'border-background-200/70 bg-background-50 hover:border-teal-100'}`}><button onClick={()=>setOpenFaq(openFaq===i?null:i)} className="w-full flex items-center justify-between px-5 py-4 text-left cursor-pointer"><span className={`font-heading font-semibold text-sm pr-4 transition-colors duration-300 ${openFaq===i?'text-teal-600':'text-foreground-900'}`}>{faq.q}</span><div className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 transition-all duration-300 ${openFaq===i?'bg-teal-500 text-white rotate-45':'bg-background-100 text-foreground-400'}`}><i className="ri-add-line text-sm"></i></div></button><div className={`transition-all duration-400 overflow-hidden ${openFaq===i?'max-h-[400px] opacity-100':'max-h-0 opacity-0'}`}><div className="px-5 pb-5 text-foreground-500 text-sm leading-relaxed">{faq.a}</div></div></div>))}</div></div></section>
      <section className="py-16 md:py-20 bg-gradient-to-r from-teal-700 to-emerald-700 relative overflow-hidden"><div className="absolute inset-0"><div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] rounded-full bg-white/5 blur-[100px]" /></div><div className="max-w-3xl mx-auto px-4 md:px-8 text-center relative z-10"><RevealBlock><h2 className="font-heading font-bold text-3xl md:text-4xl text-white mb-4">Walk Pain-Free Again</h2><p className="text-white/70 text-sm md:text-base mb-8 max-w-lg mx-auto">Your feet carry you through life. Get expert foot and ankle care from Dr. Sagar K V.</p><div className="flex flex-col sm:flex-row items-center justify-center gap-3"><a href="tel:+918197344754" className="px-8 py-3.5 bg-white text-teal-700 font-heading font-semibold rounded-full text-sm hover:bg-white/95 transition-all duration-300 whitespace-nowrap cursor-pointer"><i className="ri-phone-line mr-2"></i>Call Now</a><a href="https://wa.me/918197344754" target="_blank" rel="noopener noreferrer" className="px-8 py-3.5 bg-white/15 border border-white/25 text-white font-heading font-semibold rounded-full text-sm hover:bg-white/25 transition-all duration-300 whitespace-nowrap cursor-pointer"><i className="ri-whatsapp-line mr-2"></i>WhatsApp</a></div></RevealBlock></div></section>

      <RelatedPatientStories relevantSlugs={['knee-replacement-68']} />

      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-10"><span className="text-foreground-400 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Explore Related</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Related <span className="text-teal-600">Treatments</span></h2></RevealBlock><div className="flex flex-wrap items-center justify-center gap-3">{RELATED.map((r)=>(<Link key={r.id} to={`/treatments/${r.id}`} className="flex items-center gap-2.5 px-5 py-3 rounded-full border border-background-200/70 bg-background-50 text-foreground-600 hover:border-teal-200 hover:text-teal-600 text-sm font-medium transition-all duration-300 cursor-pointer whitespace-nowrap"><i className={`${r.icon} text-base`}></i>{r.label}</Link>))}</div></div></section>
      <Footer /><FloatingWhatsApp /><MobileStickyBar />
    </main>
  );
}
