import { useState } from 'react';
import { Link } from 'react-router-dom';
import Header from '@/components/feature/Header';
import Footer from '@/pages/home/components/Footer';
import FloatingWhatsApp from '@/pages/home/components/FloatingWhatsApp';
import MobileStickyBar from '@/pages/home/components/MobileStickyBar';
import RehabilitationHero from './HeroSection';
import { useScrollAnimation } from '@/hooks/useScrollAnimation';
import RelatedPatientStories from '@/components/feature/RelatedPatientStories';

const SYMPTOMS = [
  { icon: 'ri-emotion-sad-line', title: 'Post-Surgical Stiffness', desc: 'Joint stiffness and reduced range of motion following orthopedic surgery. Requires structured physiotherapy to restore mobility.' },
  { icon: 'ri-alert-line', title: 'Muscle Weakness', desc: 'Significant loss of strength in the operated or injured limb due to disuse. Targeted strengthening is essential for full recovery.' },
  { icon: 'ri-contrast-drop-line', title: 'Swelling', desc: 'Persistent post-operative or post-injury swelling that limits movement and delays healing. Managed with elevation, compression, and modalities.' },
  { icon: 'ri-walk-line', title: 'Gait Abnormalities', desc: 'Limping or altered walking pattern that persists after injury — often becomes a habit that needs deliberate retraining.' },
  { icon: 'ri-restart-line', title: 'Balance Problems', desc: 'Proprioceptive deficits after joint injury or surgery. Balance training prevents falls and improves confidence during movement.' },
  { icon: 'ri-emotion-happy-line', title: 'Fear of Movement', desc: 'Kinesiophobia — fear of re-injury that prevents normal activity. Psychological component of recovery that requires gradual confidence-building.' },
];

const PHASES = [
  { title: 'Phase 1: Protection', desc: 'Immediate post-surgery or post-injury phase. Focus on pain control, swelling management, and protecting the healing structures while beginning gentle movement.' },
  { title: 'Phase 2: Mobility Restoration', desc: 'Graded range-of-motion exercises to restore joint movement. Manual therapy techniques. Introduction of light resisted exercises as healing permits.' },
  { title: 'Phase 3: Strengthening', desc: 'Progressive resistance training targeting weakened muscle groups. Core stability, proprioception, and functional movement pattern retraining.' },
  { title: 'Phase 4: Return to Function', desc: 'Sport-specific or activity-specific training. Advanced balance and agility drills. Graduated return to work, sports, and recreational activities.' },
  { title: 'Phase 5: Maintenance', desc: 'Long-term exercise program to maintain gains. Periodic check-ins with Dr. Sagar to monitor progress and address any recurrent issues.' },
  { title: 'Phase 6: Prevention', desc: 'Education on injury prevention strategies, proper biomechanics, and warning signs to watch for. Empowering patients to stay healthy long-term.' },
];

const TREATMENTS = [
  { icon: 'ri-psychotherapy-line', title: 'Manual Therapy', desc: 'Hands-on techniques including joint mobilization, soft tissue massage, and myofascial release to improve mobility and reduce pain.' },
  { icon: 'ri-run-line', title: 'Therapeutic Exercise', desc: 'Customized exercise programs targeting strength, flexibility, endurance, and neuromuscular control specific to your condition and goals.' },
  { icon: 'ri-flashlight-line', title: 'Modalities', desc: 'Ultrasound, TENS, heat/cold therapy, and electrical stimulation to manage pain and promote tissue healing during early recovery phases.' },
  { icon: 'ri-restart-line', title: 'Gait Training', desc: 'Analysis and correction of walking patterns using mirrors, video feedback, and progressive weight-bearing protocols.' },
  { icon: 'ri-tools-line', title: 'Bracing & Support', desc: 'Appropriate use of braces, splints, walking aids, and orthotics during recovery — weaned off as strength and stability improve.' },
  { icon: 'ri-mental-health-line', title: 'Patient Education', desc: 'Understanding your condition, recovery expectations, and self-management strategies. Informed patients achieve better outcomes.' },
];

const BENEFITS = [
  { icon: 'ri-speed-up-line', title: 'Faster Recovery', desc: 'Structured rehabilitation following Dr. Sagar\'s protocols accelerates healing and reduces time away from work and activities.' },
  { icon: 'ri-shield-check-line', title: 'Better Outcomes', desc: 'Patients who complete prescribed rehabilitation achieve significantly better long-term results after orthopedic surgery.' },
  { icon: 'ri-shield-flash-line', title: 'Prevent Recurrence', desc: 'Addressing the biomechanical factors that contributed to the original injury prevents future problems.' },
  { icon: 'ri-restart-line', title: 'Confidence Building', desc: 'Gradual, supervised progression rebuilds trust in your body — essential for return to sports and high-level activities.' },
];

const FAQS = [
  { q: 'Why is rehabilitation necessary after orthopedic surgery?', a: 'Surgery fixes the structural problem, but rehabilitation restores function. Without proper rehab, even perfectly performed surgery can result in stiffness, weakness, and poor outcomes. Dr. Sagar\'s protocols ensure optimal recovery.' },
  { q: 'How long does orthopedic rehabilitation take?', a: 'Timelines vary by procedure: arthroscopy (4-8 weeks), fracture fixation (8-16 weeks), joint replacement (12-24 weeks), and ligament reconstruction (16-36 weeks). Dr. Sagar provides a personalized timeline at your first visit.' },
  { q: 'Can I do rehabilitation at home?', a: 'Some exercises are designed for home. However, supervised sessions ensure correct technique, appropriate progression, and early identification of problems. A combination of clinic and home exercises works best.' },
  { q: 'What happens if I skip rehabilitation?', a: 'Skipping rehab leads to stiffness, muscle wasting, poor functional outcomes, and higher risk of re-injury or failed surgery. The investment in rehabilitation pays dividends in long-term results.' },
  { q: 'When can I return to sports after surgery?', a: 'Return-to-sport decisions are based on objective criteria — not just time. You must demonstrate full range of motion, 90%+ strength compared to the uninjured side, and pass sport-specific functional tests. Rushing back is the #1 cause of re-injury.' },
  { q: 'Is physiotherapy painful?', a: 'Rehabilitation involves working through discomfort, but not severe pain. Dr. Sagar\'s team monitors your response and adjusts exercises accordingly. Pain control is always a priority during early recovery phases.' },
];

const RELATED = [
  { id: 'joint-replacement', icon: 'ri-surgical-mask-line', label: 'Joint Replacement' },
  { id: 'sports-injuries', icon: 'ri-run-line', label: 'Sports Injuries' },
  { id: 'fracture-care', icon: 'ri-shield-line', label: 'Fracture Care' },
  { id: 'knee-pain', icon: 'ri-walk-line', label: 'Knee Pain' },
];

function RevealBlock({ children, delay = '', className = '' }: { children: React.ReactNode; delay?: string; className?: string }) {
  const { ref, isVisible } = useScrollAnimation(0.1);
  return (<div ref={ref} className={`${className} transition-all duration-800 ${delay} ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>{children}</div>);
}

export default function RehabilitationPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  return (
    <main className="min-h-screen bg-background-50">
      <Header /><RehabilitationHero />
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock><div className="grid grid-cols-1 lg:grid-cols-2 gap-10 md:gap-16 items-center"><div><span className="text-amber-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Overview</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3 mb-5">The <span className="text-amber-600">Recovery Journey</span></h2><div className="space-y-4 text-foreground-600 text-sm leading-relaxed"><p>Orthopedic surgery fixes the structure — rehabilitation restores the function. The two are inseparable. <strong className="text-foreground-900">Surgery without proper rehabilitation is incomplete treatment.</strong></p><p>Dr. Sagar K V believes in structured, progressive recovery protocols that are personalized to each patient's condition, goals, and progress. Rehabilitation isn't one-size-fits-all — it's a dynamic process that evolves as you heal.</p><p>Whether you're recovering from joint replacement, fracture fixation, ligament reconstruction, or managing a chronic condition — <strong className="text-foreground-900">the right rehabilitation program is the difference between a good outcome and an excellent one.</strong></p></div></div><div className="relative"><div className="w-full aspect-[4/3] rounded-3xl overflow-hidden bg-gradient-to-br from-amber-100 via-orange-50 to-background-100 border border-background-200/70 flex items-center justify-center"><div className="text-center p-8"><div className="w-20 h-20 mx-auto mb-4 rounded-full bg-amber-100 flex items-center justify-center"><i className="ri-mental-health-line text-amber-600 text-3xl"></i></div><span className="text-foreground-400 text-sm">Rehabilitation Illustration</span></div></div></div></div></RevealBlock></div></section>
      <section className="py-16 md:py-24 bg-background-100"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-amber-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Symptoms</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Post-Surgery & Injury <span className="text-amber-600">Challenges</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">{SYMPTOMS.map((s,i)=>(<RevealBlock key={i} delay={`delay-${i*100}`}><div className="bg-background-50 border border-background-200/70 rounded-2xl p-5 md:p-6 h-full"><div className="w-10 h-10 rounded-xl bg-amber-50 flex items-center justify-center mb-4"><i className={`${s.icon} text-amber-600 text-lg`}></i></div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-2">{s.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{s.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-amber-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Recovery Phases</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Structured <span className="text-amber-600">Rehabilitation</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{PHASES.map((p,i)=>(<RevealBlock key={i} delay={`delay-${i*80}`}><div className="flex gap-4 p-5 rounded-2xl border border-background-200/70 bg-background-50 hover:border-amber-200/50 transition-all duration-300 group cursor-default"><div className="w-2 rounded-full bg-amber-400/40 group-hover:bg-amber-500 shrink-0 transition-colors duration-300" /><div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-1.5">{p.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{p.desc}</p></div></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-secondary-600 relative overflow-hidden"><div className="absolute inset-0 pointer-events-none"><div className="absolute top-0 right-0 w-96 h-96 rounded-full bg-amber-500/8 blur-[120px]" /></div><div className="max-w-6xl mx-auto px-4 md:px-8 relative z-10"><RevealBlock className="text-center mb-12"><span className="text-amber-400 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Rehab Methods</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-white mt-3">Our <span className="text-amber-400">Approach</span></h2></RevealBlock><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">{TREATMENTS.map((t,i)=>(<RevealBlock key={i} delay={`delay-${i*80}`}><div className="glass-dark rounded-2xl p-5 md:p-6 h-full group hover:-translate-y-1 transition-all duration-400"><div className="w-11 h-11 rounded-xl bg-amber-400/15 flex items-center justify-center mb-4 group-hover:bg-amber-400/25 transition-colors duration-300"><i className={`${t.icon} text-amber-300 text-xl`}></i></div><h3 className="font-heading font-semibold text-white text-sm mb-2">{t.title}</h3><p className="text-white/45 text-xs leading-relaxed">{t.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-12"><span className="text-amber-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Why Rehab Matters</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Benefits of <span className="text-amber-600">Structured Rehab</span></h2></RevealBlock><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-5">{BENEFITS.map((b,i)=>(<RevealBlock key={i} delay={`delay-${i*100}`}><div className="text-center p-6 rounded-2xl border border-background-200/70 bg-background-50"><div className="w-14 h-14 mx-auto mb-4 rounded-full bg-amber-50 flex items-center justify-center"><i className={`${b.icon} text-amber-600 text-2xl`}></i></div><h3 className="font-heading font-semibold text-foreground-900 text-sm mb-2">{b.title}</h3><p className="text-foreground-500 text-xs leading-relaxed">{b.desc}</p></div></RevealBlock>))}</div></div></section>
      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-3xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-10"><span className="text-amber-600 font-heading font-semibold text-xs tracking-[0.2em] uppercase">FAQ</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Rehabilitation <span className="text-amber-600">Questions</span></h2></RevealBlock><div className="space-y-3">{FAQS.map((faq,i)=>(<div key={i} className={`border rounded-2xl overflow-hidden transition-all duration-300 ${openFaq===i?'border-amber-200 bg-background-50':'border-background-200/70 bg-background-50 hover:border-amber-100'}`}><button onClick={()=>setOpenFaq(openFaq===i?null:i)} className="w-full flex items-center justify-between px-5 py-4 text-left cursor-pointer"><span className={`font-heading font-semibold text-sm pr-4 transition-colors duration-300 ${openFaq===i?'text-amber-600':'text-foreground-900'}`}>{faq.q}</span><div className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 transition-all duration-300 ${openFaq===i?'bg-amber-500 text-white rotate-45':'bg-background-100 text-foreground-400'}`}><i className="ri-add-line text-sm"></i></div></button><div className={`transition-all duration-400 overflow-hidden ${openFaq===i?'max-h-[400px] opacity-100':'max-h-0 opacity-0'}`}><div className="px-5 pb-5 text-foreground-500 text-sm leading-relaxed">{faq.a}</div></div></div>))}</div></div></section>
      <section className="py-16 md:py-20 bg-gradient-to-r from-amber-600 to-orange-600 relative overflow-hidden"><div className="absolute inset-0"><div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] rounded-full bg-white/5 blur-[100px]" /></div><div className="max-w-3xl mx-auto px-4 md:px-8 text-center relative z-10"><RevealBlock><h2 className="font-heading font-bold text-3xl md:text-4xl text-white mb-4">Start Your Recovery Today</h2><p className="text-white/70 text-sm md:text-base mb-8 max-w-lg mx-auto">Whether post-surgery or managing a chronic condition, Dr. Sagar K V provides structured rehabilitation for optimal recovery.</p><div className="flex flex-col sm:flex-row items-center justify-center gap-3"><a href="tel:+918197344754" className="px-8 py-3.5 bg-white text-amber-700 font-heading font-semibold rounded-full text-sm hover:bg-white/95 transition-all duration-300 whitespace-nowrap cursor-pointer"><i className="ri-phone-line mr-2"></i>Call Now</a><a href="https://wa.me/918197344754" target="_blank" rel="noopener noreferrer" className="px-8 py-3.5 bg-white/15 border border-white/25 text-white font-heading font-semibold rounded-full text-sm hover:bg-white/25 transition-all duration-300 whitespace-nowrap cursor-pointer"><i className="ri-whatsapp-line mr-2"></i>WhatsApp</a></div></RevealBlock></div></section>

      <RelatedPatientStories relevantSlugs={['knee-replacement-68', 'shoulder-arthroscopy-42', 'spine-surgery-55']} />

      <section className="py-16 md:py-24 bg-background-50"><div className="max-w-6xl mx-auto px-4 md:px-8"><RevealBlock className="text-center mb-10"><span className="text-foreground-400 font-heading font-semibold text-xs tracking-[0.2em] uppercase">Explore Related</span><h2 className="font-heading font-bold text-3xl md:text-4xl text-foreground-900 mt-3">Related <span className="text-amber-600">Treatments</span></h2></RevealBlock><div className="flex flex-wrap items-center justify-center gap-3">{RELATED.map((r)=>(<Link key={r.id} to={`/treatments/${r.id}`} className="flex items-center gap-2.5 px-5 py-3 rounded-full border border-background-200/70 bg-background-50 text-foreground-600 hover:border-amber-200 hover:text-amber-600 text-sm font-medium transition-all duration-300 cursor-pointer whitespace-nowrap"><i className={`${r.icon} text-base`}></i>{r.label}</Link>))}</div></div></section>
      <Footer /><FloatingWhatsApp /><MobileStickyBar />
    </main>
  );
}
